// Auto-generated from https://www.coraltraits.org/traits.
// Public data, CC-BY 4.0. Each trait id resolves to coraltraits.org/traits/{id}.
export interface CoralTrait { id: number; name: string; }
export interface CoralTraitCategory { name: string; traits: CoralTrait[]; }

export const CORAL_TRAITS_URL = "https://www.coraltraits.org/traits";

export const CORAL_TRAIT_CATEGORIES: CoralTraitCategory[] = [
  { name: "Biomechanical", traits: [
    { id: 583, name: "Axis presence" },
    { id: 614, name: "CaCO3 concentration in sclerites" },
    { id: 616, name: "CaCO3 concentration in the axis" },
    { id: 511, name: "Calcareous sclerites presence" },
    { id: 615, name: "Ca/Mg ratio in sclerites" },
    { id: 137, name: "Colony shape factor" },
    { id: 169, name: "Larval swimming speed" },
    { id: 619, name: "Main non-scleritic skeletal component" },
    { id: 598, name: "Main skeletal component of sclerites" },
    { id: 618, name: "Mg/Ca ratio in sclerites" },
    { id: 622, name: "MgCO3 concentration in axis" },
    { id: 510, name: "MgCO3 concentration in sclerites" },
    { id: 620, name: "Mg concentration in axis" },
    { id: 61, name: "Skeletal density" },
    { id: 179, name: "Skeletal micro-density" },
    { id: 632, name: "Skeletal rigidity" },
    { id: 617, name: "Stiffness Young's modulus" },
    { id: 103, name: "Substrate attachment" },
    { id: 561, name: "Type of skeleton" },
  ] },
  { name: "Conservation", traits: [
    { id: 77, name: "IUCN Red List category" },
  ] },
  { name: "Contextual", traits: [
    { id: 159, name: "Axial corallite part" },
    { id: 207, name: "Bleaching event" },
    { id: 519, name: "Branch age class" },
    { id: 508, name: "Branch order" },
    { id: 203, name: "Colony bleached" },
    { id: 527, name: "Colony gender" },
    { id: 537, name: "Colony ID" },
    { id: 162, name: "Colony part" },
    { id: 231, name: "Colony surface area" },
    { id: 201, name: "Damage" },
    { id: 608, name: "Date" },
    { id: 242, name: "Date of previous full moon" },
    { id: 236, name: "Day" },
    { id: 243, name: "Days after previous full moon" },
    { id: 204, name: "Depth transplanted from" },
    { id: 170, name: "Direction" },
    { id: 192, name: "Dissolved oxygen concentration" },
    { id: 156, name: "Distance from crest" },
    { id: 190, name: "Distance from shore" },
    { id: 157, name: "Distance from tip" },
    { id: 191, name: "Downward flux of suspended particulate matter" },
    { id: 239, name: "End time" },
    { id: 230, name: "Fish association controlled" },
    { id: 189, name: "Fish predation controlled" },
    { id: 154, name: "Flow rate" },
  ] },
  { name: "Ecological", traits: [
    { id: 65, name: "Abundance GBR" },
    { id: 89, name: "Abundance world" },
    { id: 574, name: "Colony contractability" },
    { id: 92, name: "Depth lower" },
    { id: 91, name: "Depth upper" },
    { id: 579, name: "Depth zone" },
    { id: 584, name: "Feeding mechanism" },
    { id: 599, name: "Food sources" },
    { id: 79, name: "Generation time" },
    { id: 233, name: "Life history strategy" },
    { id: 629, name: "Light zone" },
    { id: 601, name: "Size of prey items" },
    { id: 568, name: "Type locality depth" },
    { id: 97, name: "Water clarity preference" },
    { id: 96, name: "Wave exposure preference" },
  ] },
  { name: "Geographical", traits: [
    { id: 564, name: "Climate zone" },
    { id: 165, name: "Eastern-most range edge" },
    { id: 35, name: "Geographical region" },
    { id: 218, name: "Indo-Pacific faunal province" },
    { id: 578, name: "Marine province" },
    { id: 577, name: "Marine realm" },
    { id: 167, name: "Northern-most range edge" },
    { id: 40, name: "Ocean basin" },
    { id: 138, name: "Range size" },
    { id: 168, name: "Southern-most range edge" },
    { id: 166, name: "Western-most range edge" },
  ] },
  { name: "Morphological", traits: [
    { id: 567, name: "Branch diameter" },
    { id: 560, name: "Branching architecture" },
    { id: 558, name: "Calyx height" },
    { id: 565, name: "Calyx width" },
    { id: 104, name: "Coloniality" },
    { id: 155, name: "Colony area" },
    { id: 506, name: "Colony height" },
    { id: 90, name: "Colony maximum diameter" },
    { id: 229, name: "Colony surface relief index" },
    { id: 631, name: "Colony width" },
    { id: 590, name: "Coordination of polyps" },
    { id: 213, name: "Corallite width" },
    { id: 182, name: "Corallite width maximum" },
    { id: 181, name: "Corallite width minimum" },
    { id: 535, name: "Diameter of axis skeleton" },
  ] },
  { name: "Phylogenetic", traits: [
    { id: 116, name: "Genus fossil age" },
    { id: 208, name: "Genus fossil stage" },
    { id: 164, name: "Species age phylogeny" },
  ] },
  { name: "Physiological", traits: [
    { id: 625, name: "Axis radial growth rate" },
    { id: 31, name: "Bleaching susceptibility" },
    { id: 127, name: "Calcification rate" },
    { id: 602, name: "Capture rate" },
    { id: 507, name: "Colony age" },
    { id: 133, name: "Dark respiration" },
    { id: 134, name: "Gross photosynthesis" },
    { id: 60, name: "Growth rate" },
    { id: 553, name: "Longevity" },
    { id: 147, name: "Mitotic index" },
    { id: 559, name: "Photosynthesis/respiration ratio (P/R)" },
    { id: 149, name: "Protein biomass" },
    { id: 128, name: "Symbiodinium clade" },
    { id: 135, name: "Symbiodinium density" },
    { id: 129, name: "Symbiodinium subclade" },
    { id: 604, name: "Symbiont density" },
    { id: 132, name: "Tissue thickness" },
    { id: 41, name: "Zooxanthellate" },
  ] },
  { name: "Reproductive", traits: [
    { id: 47, name: "Age at maturity" },
    { id: 556, name: "Asexual reproduction mode" },
    { id: 216, name: "Colony fecundity" },
    { id: 217, name: "Egg size" },
    { id: 211, name: "Eggs per area" },
    { id: 552, name: "Frequency of reproduction" },
    { id: 51, name: "Initiation oogenic cycle" },
    { id: 53, name: "Initiation spermatogenic cycle" },
    { id: 114, name: "Laboratory PLD max" },
    { id: 515, name: "Larval length" },
    { id: 10, name: "Larval time to motility" },
    { id: 516, name: "Larval width" },
    { id: 215, name: "Length of nonreproductive zone" },
    { id: 50, name: "Length oogenic cycle max" },
    { id: 52, name: "Length spermatogenic cycle" },
    { id: 214, name: "Mature egg diameter" },
    { id: 209, name: "Mesentery fecundity" },
    { id: 5, name: "Mode of larval development" },
    { id: 11, name: "Oocyte size at maturity" },
    { id: 623, name: "Oogenic cycle duration" },
    { id: 536, name: "Planktonic phase duration in larvae" },
    { id: 12, name: "Polyp fecundity" },
    { id: 184, name: "Propagule size on release" },
    { id: 212, name: "Ratio of female to male gonads" },
    { id: 234, name: "Reproductive condition" },
  ] },
  { name: "Stoichiometric", traits: [
    { id: 146, name: "Chlorophyll a" },
    { id: 131, name: "Lipid content" },
    { id: 186, name: "Nitrogen concentration" },
    { id: 187, name: "Phosphorus concentration" },
    { id: 188, name: "RNA:DNA ratio" },
    { id: 150, name: "Total biomass" },
  ] },
];

// Derived at module load to stay in sync with the dataset.
export const CORAL_TRAITS_TOTAL = CORAL_TRAIT_CATEGORIES.reduce((n, c) => n + c.traits.length, 0);
